// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu1ixPeMQrfwE9omWQg_4JiGLyqrl6S4A',
    appId: '1:637895004896:web:5456fe6f19c72d8f573685',
    messagingSenderId: '637895004896',
    projectId: 'task-management-4f2c1',
    authDomain: 'task-management-4f2c1.firebaseapp.com',
    storageBucket: 'task-management-4f2c1.firebasestorage.app',
    measurementId: 'G-WWVGMS75G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgX41iAqbnFV1AcmOhUNsqXkWE4tGAVTE',
    appId: '1:637895004896:android:03deb3e7431efcf1573685',
    messagingSenderId: '637895004896',
    projectId: 'task-management-4f2c1',
    storageBucket: 'task-management-4f2c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDBcwmBOId2m89E3a89r5gsFfxbxC1Mqc',
    appId: '1:637895004896:ios:cff2e4c8efff0a81573685',
    messagingSenderId: '637895004896',
    projectId: 'task-management-4f2c1',
    storageBucket: 'task-management-4f2c1.firebasestorage.app',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDBcwmBOId2m89E3a89r5gsFfxbxC1Mqc',
    appId: '1:637895004896:ios:cff2e4c8efff0a81573685',
    messagingSenderId: '637895004896',
    projectId: 'task-management-4f2c1',
    storageBucket: 'task-management-4f2c1.firebasestorage.app',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu1ixPeMQrfwE9omWQg_4JiGLyqrl6S4A',
    appId: '1:637895004896:web:61747c1dd406fa5a573685',
    messagingSenderId: '637895004896',
    projectId: 'task-management-4f2c1',
    authDomain: 'task-management-4f2c1.firebaseapp.com',
    storageBucket: 'task-management-4f2c1.firebasestorage.app',
    measurementId: 'G-CSNHYTVMWE',
  );
}
